[theme]
# Primary accent color for interactive elements
primaryColor="#48429A"

backgroundColor="#55C1AF"

# background color used for most interactive widgets
secondaryBackgroundColor="#48429A"

textColor="#ffffff"

font='sans serif'
